FROM python:3.12-slim
RUN apt-get update && apt-get install -y build-essential curl
WORKDIR /app
COPY . .
RUN pip install "fastapi[standard]" uvicorn pandas scikit-learn joblib pydantic \
    && pip install --no-deps .
EXPOSE 8000
CMD ["uvicorn", "fraud_service.api.app:app", "--host", "0.0.0.0", "--port", "8000"]